
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse
    username: root
    password: Hoangdo@123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 32
      idle-timeout: 10000
  profiles:
    include: common
